apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: your@email.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      # Name is arbitrary.
      name: acme-issuer-account-key

    solvers:
    # example: cross-account zone management for example.com
    # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
    # to assume a role in a different account
    - selector:
        dnsZones:
          # wild-card domains are easy to do:
          - "*.your-domain.com"
      dns01:
        route53:
          # This section needs to be filled in with your
          # data from Route53 and your IAM account that's
          # tasked with handling changes to DNS.
          # @see https://cert-manager.io/docs/configuration/acme/dns01/route53/
          region: us-west-2
          hostedZoneID: Z?????????? # optional, see policy above
          role: arn:aws:iam::8**********:role/acme-cert-manager 
          accessKeyID: AKIA3V******
          secretAccessKeySecretRef:
            name: staging-route53-credentials
            key: secret-access-key
