apiVersion: v1
data:
  index.html: "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n
    \   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n
    \   <meta name=\"description\" content=\"\">\n    <meta name=\"author\" content=\"Mark
    Otto, Jacob Thornton, and Bootstrap contributors\">\n    <meta name=\"generator\"
    content=\"Hugo 0.83.1\">\n    <title>Kubernetes is the Jumbotron</title>\n\n    <link
    rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/jumbotron/\">\n
    \ \n    \n\n    <!-- Bootstrap core CSS -->\n<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\"
    rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\"
    crossorigin=\"anonymous\">\n\n    <style>\n      .bd-placeholder-img {\n        font-size:
    1.125rem;\n        text-anchor: middle;\n        -webkit-user-select: none;\n
    \       -moz-user-select: none;\n        user-select: none;\n      }\n\n      @media
    (min-width: 768px) {\n        .bd-placeholder-img-lg {\n          font-size: 3.5rem;\n
    \       }\n      }\n    </style>\n\n    \n  </head>\n  <body>\n    \n<main>\n
    \ <div class=\"container py-4\">\n    <header class=\"pb-3 mb-4 border-bottom\">\n
    \     <a href=\"/\" class=\"d-flex align-items-center text-dark text-decoration-none\">\n
    \       <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"32\" class=\"me-2\"
    viewBox=\"0 0 118 94\" role=\"img\"><title>Bootstrap</title><path fill-rule=\"evenodd\"
    clip-rule=\"evenodd\" d=\"M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064
    14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649
    10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51
    94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504
    5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214
    5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2
    0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01
    10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884
    0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167
    0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z\" fill=\"currentColor\"></path></svg>\n
    \       <span class=\"fs-4\">Ingress Nginx and Cert-Manager</span>\n      </a>\n
    \   </header>\n\n    <div class=\"p-5 mb-4 bg-light rounded-3\">\n      <div class=\"container-fluid
    py-5\">\n        <h1 class=\"display-5 fw-bold\">Demoing Let's Encrypt</h1>\n
    \       <p class=\"col-md-8 fs-4\">This is a demo of serving web content from
    a Kubernetes nginx pod, going out to you via the Ingress Nginx Ingress Controller.
    We've rigged up Cert-Manager and Let's Encrypt so that you're getting a secure
    web page using a real certificate.</p>\n        <p>Thanks to the Bootstrap 5 team
    for letting us borrow their Jumbotron demo page!</p>\n        <button class=\"btn
    btn-primary btn-lg\" type=\"button\">Example button</button>\n      </div>\n    </div>\n\n
    \   <div class=\"row align-items-md-stretch\">\n      <div class=\"col-md-6\">\n
    \       <div class=\"h-100 p-5 text-white bg-dark rounded-3\">\n          <h2>Change
    the background</h2>\n          <p>Swap the background-color utility and add a
    `.text-*` color utility to mix up the jumbotron look. Then, mix and match with
    additional component themes and more.</p>\n          <button class=\"btn btn-outline-light\"
    type=\"button\">Example button</button>\n        </div>\n      </div>\n      <div
    class=\"col-md-6\">\n        <div class=\"h-100 p-5 bg-light border rounded-3\">\n
    \         <h2>Add borders</h2>\n          <p>Or, keep it light and add a border
    for some added definition to the boundaries of your content. Be sure to look under
    the hood at the source HTML here as we've adjusted the alignment and sizing of
    both column's content for equal-height.</p>\n          <button class=\"btn btn-outline-secondary\"
    type=\"button\">Example button</button>\n        </div>\n      </div>\n    </div>\n\n
    \   <footer class=\"pt-3 mt-4 text-muted border-top\">\n      &copy; 2021\n    </footer>\n
    \ </div>\n</main>\n\n\n    \n  </body>\n</html>\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: web-data
